apiVersion: skaffold/v2beta6
kind: Config
deploy:
  kubectl:
    manifests:
      - ./k8s/*
build:
  googleCloudBuild:
    projectId: kubernetes-deployment-360515
  artifacts:
    - image: gcr.io/souravdeveloper/ecom-auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: gcr.io/souravdeveloper/ecom-product
      context: product
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
